# Generated by Django 5.2.5 on 2025-08-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('current_lat', models.FloatField(default=0.0)),
                ('current_lng', models.FloatField(default=0.0)),
                ('speed', models.FloatField(default=0.0)),
            ],
        ),
    ]
