# Generated by Django 5.2.5 on 2025-08-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus'),
        ),
    ]
